name: iNotes
options:
  bundleIdPrefix: com.inotes
  deploymentTarget:
    macOS: "14.0"
targets:
  iNotes:
    type: application
    platform: macOS
    sources:
      - iNotes
    settings:
      base:
        INFOPLIST_FILE: iNotes/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.inotes.inotes
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets:
        - iNotesTests
  iNotesTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - iNotesTests
    dependencies:
      - target: iNotes
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.inotes.inotesTests
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: "YES"
